// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kurapayload.proto

package org.eclipse.kura.core.message.protobuf;

public interface KuraPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kuradatatypes.KuraPayload)
    com.google.protobuf.GeneratedMessageV3.
        ExtendableMessageOrBuilder<KuraPayload> {

  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional .kuradatatypes.KuraPayload.KuraPosition position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>optional .kuradatatypes.KuraPayload.KuraPosition position = 2;</code>
   * @return The position.
   */
  KuraPayload.KuraPosition getPosition();
  /**
   * <code>optional .kuradatatypes.KuraPayload.KuraPosition position = 2;</code>
   */
  KuraPayload.KuraPositionOrBuilder getPositionOrBuilder();

  /**
   * <pre>
   * can be zero, so optional
   * </pre>
   *
   * <code>repeated .kuradatatypes.KuraPayload.KuraMetric metric = 5000;</code>
   */
  java.util.List<KuraPayload.KuraMetric>
      getMetricList();
  /**
   * <pre>
   * can be zero, so optional
   * </pre>
   *
   * <code>repeated .kuradatatypes.KuraPayload.KuraMetric metric = 5000;</code>
   */
  KuraPayload.KuraMetric getMetric(int index);
  /**
   * <pre>
   * can be zero, so optional
   * </pre>
   *
   * <code>repeated .kuradatatypes.KuraPayload.KuraMetric metric = 5000;</code>
   */
  int getMetricCount();
  /**
   * <pre>
   * can be zero, so optional
   * </pre>
   *
   * <code>repeated .kuradatatypes.KuraPayload.KuraMetric metric = 5000;</code>
   */
  java.util.List<? extends KuraPayload.KuraMetricOrBuilder>
      getMetricOrBuilderList();
  /**
   * <pre>
   * can be zero, so optional
   * </pre>
   *
   * <code>repeated .kuradatatypes.KuraPayload.KuraMetric metric = 5000;</code>
   */
  KuraPayload.KuraMetricOrBuilder getMetricOrBuilder(
      int index);

  /**
   * <code>optional bytes body = 5001;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>optional bytes body = 5001;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
