// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kurapayload.proto

package org.eclipse.kura.core.message.protobuf;

public final class KuraPayloadProto {
  private KuraPayloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kuradatatypes_KuraPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kuradatatypes_KuraPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kuradatatypes_KuraPayload_KuraMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kuradatatypes_KuraPayload_KuraMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kuradatatypes_KuraPayload_KuraPosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kuradatatypes_KuraPayload_KuraPosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021kurapayload.proto\022\rkuradatatypes\"\243\005\n\013K" +
      "uraPayload\022\021\n\ttimestamp\030\001 \001(\003\0229\n\010positio" +
      "n\030\002 \001(\0132\'.kuradatatypes.KuraPayload.Kura" +
      "Position\0226\n\006metric\030\210\' \003(\0132%.kuradatatype" +
      "s.KuraPayload.KuraMetric\022\r\n\004body\030\211\' \001(\014\032" +
      "\305\002\n\nKuraMetric\022\014\n\004name\030\001 \002(\t\022=\n\004type\030\002 \002" +
      "(\0162/.kuradatatypes.KuraPayload.KuraMetri" +
      "c.ValueType\022\024\n\014double_value\030\003 \001(\001\022\023\n\013flo" +
      "at_value\030\004 \001(\002\022\022\n\nlong_value\030\005 \001(\003\022\021\n\tin" +
      "t_value\030\006 \001(\005\022\022\n\nbool_value\030\007 \001(\010\022\024\n\014str" +
      "ing_value\030\010 \001(\t\022\023\n\013bytes_value\030\t \001(\014\"Y\n\t" +
      "ValueType\022\n\n\006DOUBLE\020\000\022\t\n\005FLOAT\020\001\022\t\n\005INT6" +
      "4\020\002\022\t\n\005INT32\020\003\022\010\n\004BOOL\020\004\022\n\n\006STRING\020\005\022\t\n\005" +
      "BYTES\020\006\032\257\001\n\014KuraPosition\022\020\n\010latitude\030\001 \002" +
      "(\001\022\021\n\tlongitude\030\002 \002(\001\022\020\n\010altitude\030\003 \001(\001\022" +
      "\021\n\tprecision\030\004 \001(\001\022\017\n\007heading\030\005 \001(\001\022\r\n\005s" +
      "peed\030\006 \001(\001\022\021\n\ttimestamp\030\007 \001(\003\022\022\n\nsatelli" +
      "tes\030\010 \001(\005\022\016\n\006status\030\t \001(\005*\005\010\003\020\210\'B<\n&org." +
      "eclipse.kura.core.message.protobufB\020Kura" +
      "PayloadProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kuradatatypes_KuraPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kuradatatypes_KuraPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kuradatatypes_KuraPayload_descriptor,
        new String[] { "Timestamp", "Position", "Metric", "Body", });
    internal_static_kuradatatypes_KuraPayload_KuraMetric_descriptor =
      internal_static_kuradatatypes_KuraPayload_descriptor.getNestedTypes().get(0);
    internal_static_kuradatatypes_KuraPayload_KuraMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kuradatatypes_KuraPayload_KuraMetric_descriptor,
        new String[] { "Name", "Type", "DoubleValue", "FloatValue", "LongValue", "IntValue", "BoolValue", "StringValue", "BytesValue", });
    internal_static_kuradatatypes_KuraPayload_KuraPosition_descriptor =
      internal_static_kuradatatypes_KuraPayload_descriptor.getNestedTypes().get(1);
    internal_static_kuradatatypes_KuraPayload_KuraPosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kuradatatypes_KuraPayload_KuraPosition_descriptor,
        new String[] { "Latitude", "Longitude", "Altitude", "Precision", "Heading", "Speed", "Timestamp", "Satellites", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
